package §_-p2z§
{
   public class §_-11m§
   {
      
      public static const §_-T1e§:String = "<particleEmitterConfig>" + "<absolutePosition value=\"0\"></absolutePosition>" + "<yCoordFlipped value=\"1\"></yCoordFlipped>" + "<sourcePosition x=\"0.00\" y=\"0.00\"></sourcePosition>" + "<sourcePositionVariance x=\"7.00\" y=\"7.00\"></sourcePositionVariance>" + "<speed value=\"152.51\"></speed>" + "<speedVariance value=\"148.29\"></speedVariance>" + "<particleLifeSpan value=\"1.0726\"></particleLifeSpan>" + "<particleLifespanVariance value=\"0.0000\"></particleLifespanVariance>" + "<angle value=\"270.0\"></angle>" + "<angleVariance value=\"0.00\"></angleVariance>" + "<gravity x=\"0.00\" y=\"0.00\"></gravity>" + "<radialAcceleration value=\"0.00\"></radialAcceleration>" + "<tangentialAcceleration value=\"0.00\"></tangentialAcceleration>" + "<radialAccelVariance value=\"0.00\"></radialAccelVariance>" + "<tangentialAccelVariance value=\"0.00\"></tangentialAccelVariance>" + "<startColor red=\"1.00\" green=\"0.16\" blue=\"0.07\" alpha=\"0.79\"></startColor>" + "<startColorVariance red=\"0.12\" green=\"0.00\" blue=\"0.00\" alpha=\"0.18\"></startColorVariance>" + "<finishColor red=\"0.93\" green=\"0.34\" blue=\"0.21\" alpha=\"0.00\"></finishColor>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></finishColorVariance>" + "<maxParticles value=\"77\"></maxParticles>" + "<startParticleSize value=\"64.00\"></startParticleSize>" + "<startParticleSizeVariance value=\"5.00\"></startParticleSizeVariance>" + "<finishParticleSize value=\"1.39\"></finishParticleSize>" + "<finishParticleSizeVariance value=\"0.00\"></finishParticleSizeVariance>" + "<duration value=\"-1.00\"></duration>" + "<emitterType value=\"0\"></emitterType>" + "<maxRadius value=\"287.37\"></maxRadius>" + "<maxRadiusVariance value=\"331.58\"></maxRadiusVariance>" + "<minRadius value=\"60.00\"></minRadius>" + "<minRadiusVariance value=\"0.00\"></minRadiusVariance>" + "<rotatePerSecond value=\"116.05\"></rotatePerSecond>" + "<rotatePerSecondVariance value=\"0.00\"></rotatePerSecondVariance>" + "<blendFuncSource value=\"1\"></blendFuncSource>" + "<blendFuncDestination value=\"772\"></blendFuncDestination>" + "<rotationStart value=\"0.00\"></rotationStart>" + "<rotationStartVariance value=\"0.00\"></rotationStartVariance>" + "<rotationEnd value=\"0.00\"></rotationEnd>" + "<rotationEndVariance value=\"0.00\"></rotationEndVariance>" + "</particleEmitterConfig>";
      
      public static const §_-53b§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"></sourcePosition>" + "<sourcePositionVariance x=\"0\" y=\"4\"/>" + "<speed value=\"120\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"0.87\"/>" + "<particleLifespanVariance value=\"0\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"171.43\"/>" + "<gravity x=\"0\" y=\"-100\"/>" + "<radialAcceleration value=\"-100\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"100\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"0\" green=\"0.99\" blue=\"0.99\" alpha=\"1\"/>" + "<startColorVariance red=\"0\" green=\"0.18\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"110\"/>" + "<startParticleSize value=\"4.13\"/>" + "<startParticleSizeVariance value=\"22.79\"/>" + "<finishParticleSize value=\"18.740000000000002\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"3\"/>" + "<maxRadiusVariance value=\"3\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"770\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public static const §_-zb§:String = "<particleEmitterConfig>" + "<absolutePosition value=\"0\"></absolutePosition>" + "<yCoordFlipped value=\"1\"></yCoordFlipped>" + "<sourcePosition x=\"0.00\" y=\"0.00\"></sourcePosition>" + "<sourcePositionVariance x=\"8.00\" y=\"8.00\"></sourcePositionVariance>" + "<speed value=\"6.58\"></speed>" + "<speedVariance value=\"2.00\"></speedVariance>" + "<particleLifeSpan value=\"0.8920\"></particleLifeSpan>" + "<particleLifespanVariance value=\"0.4132\"></particleLifespanVariance>" + "<angle value=\"0.00\"></angle>" + "<angleVariance value=\"0.00\"></angleVariance>" + "<gravity x=\"1.00\" y=\"1.00\"></gravity>" + "<radialAcceleration value=\"-1315.12\"></radialAcceleration>" + "<tangentialAcceleration value=\"494.57\"></tangentialAcceleration>" + "<radialAccelVariance value=\"-935.27\"></radialAccelVariance>" + "<tangentialAccelVariance value=\"513.16\"></tangentialAccelVariance>" + "<startColor red=\"0.95\" green=\"0.70\" blue=\"0.14\" alpha=\"0.10\"></startColor>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></startColorVariance>" + "<finishColor red=\"0.14\" green=\"0.09\" blue=\"0.01\" alpha=\"1.00\"></finishColor>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.10\"></finishColorVariance>" + "<maxParticles value=\"192\"></maxParticles>" + "<startParticleSize value=\"7.00\"></startParticleSize>" + "<startParticleSizeVariance value=\"0.00\"></startParticleSizeVariance>" + "<finishParticleSize value=\"12.95\"></finishParticleSize>" + "<finishParticleSizeVariance value=\"0.00\"></finishParticleSizeVariance>" + "<duration value=\"-1.00\"></duration>" + "<emitterType value=\"0\"></emitterType>" + "<maxRadius value=\"0.00\"></maxRadius>" + "<maxRadiusVariance value=\"72.63\"></maxRadiusVariance>" + "<minRadius value=\"0.00\"></minRadius>" + "<minRadiusVariance value=\"0.00\"></minRadiusVariance>" + "<rotatePerSecond value=\"0.00\"></rotatePerSecond>" + "<rotatePerSecondVariance value=\"153.95\"></rotatePerSecondVariance>" + "<blendFuncSource value=\"770\"></blendFuncSource>" + "<blendFuncDestination value=\"1\"></blendFuncDestination>" + "<rotationStart value=\"0.00\"></rotationStart>" + "<rotationStartVariance value=\"0.00\"></rotationStartVariance>" + "<rotationEnd value=\"0.00\"></rotationEnd>" + "<rotationEndVariance value=\"0.00\"></rotationEndVariance>" + "</particleEmitterConfig>";
      
      public static const §_-33W§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"35.00\"/>" + "<sourcePositionVariance x=\"7\" y=\"7\"/>" + "<speed value=\"-152.51\"/>" + "<speedVariance value=\"-147.92000000000002\"/>" + "<particleLifeSpan value=\"1.0726\"/>" + "<particleLifespanVariance value=\"0\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"10\"/>" + "<gravity x=\"0\" y=\"0\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"0.22\" green=\"0.19\" blue=\"0.23\" alpha=\"0.5\"/>" + "<startColorVariance red=\"0.21\" green=\"0.22\" blue=\"0.19\" alpha=\"0.2\"/>" + "<finishColor red=\"0.15\" green=\"0.18\" blue=\"0.21\" alpha=\"0\"/>" + "<finishColorVariance red=\"0.17\" green=\"0.18\" blue=\"0.18\" alpha=\"0\"/>" + "<maxParticles value=\"77\"/>" + "<startParticleSize value=\"15.05\"/>" + "<startParticleSizeVariance value=\"5\"/>" + "<finishParticleSize value=\"1.39\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"287.37\"/>" + "<maxRadiusVariance value=\"331.58\"/>" + "<minRadius value=\"60\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"116.05\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"772\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public function §_-11m§()
      {
         super();
      }
   }
}

