package §_-p2z§
{
   public class §_-Y2Q§
   {
      
      public static const §_-o2t§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"7\" y=\"7\"/>" + "<speed value=\"410\"/>" + "<speedVariance value=\"30\"/>" + "<particleLifeSpan value=\"0.43\"/>" + "<particleLifespanVariance value=\"0.58\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"5.71\"/>" + "<gravity x=\"0\" y=\"0\"/>" + "<radialAcceleration value=\"-235.29\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"0\" blue=\"0\" alpha=\"1\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0.4\"/>" + "<finishColor red=\"0.77\" green=\"0.5\" blue=\"0\" alpha=\"0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"1\"/>" + "<maxParticles value=\"236.06\"/>" + "<startParticleSize value=\"0\"/>" + "<startParticleSizeVariance value=\"16.12\"/>" + "<finishParticleSize value=\"66.59\"/>" + "<FinishParticleSizeVariance value=\"10\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"400\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"770\"/>" + "<blendFuncDestination value=\"1\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"194.95\"/>" + "<rotationEnd value=\"117.3\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public static const §_-Y8§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"0\"/>" + "<speed value=\"350\"/>" + "<speedVariance value=\"30\"/>" + "<particleLifeSpan value=\"0.58\"/>" + "<particleLifespanVariance value=\"0.16\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"5.43\"/>" + "<gravity x=\"0\" y=\"0\"/>" + "<radialAcceleration value=\"-258.82\"/>" + "<tangentialAcceleration value=\"5.88\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"0\" blue=\"0\" alpha=\"1\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0.4\"/>" + "<finishColor red=\"0.77\" green=\"0.5\" blue=\"0\" alpha=\"0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"1\"/>" + "<maxParticles value=\"86.21000000000001\"/>" + "<startParticleSize value=\"9.83\"/>" + "<startParticleSizeVariance value=\"9.69\"/>" + "<finishParticleSize value=\"27.83\"/>" + "<FinishParticleSizeVariance value=\"70\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"0\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public function §_-Y2Q§()
      {
         super();
      }
   }
}

