package §_-p2z§
{
   public class §_-X0§
   {
      
      public static const §_-D2G§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"37.5\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"0.67\"/>" + "<particleLifespanVariance value=\"0.96\"/>" + "<angle value=\"182.69\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"-105.23\" y=\"-0.58\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"1\" blue=\"1\" alpha=\"1\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"8.00\"/>" + "<startParticleSize value=\"18.43\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"7.43\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"100\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "<texture name=\"texture.png\"/>" + "</particleEmitterConfig>";
      
      public static const §_-31i§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"37.5\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"0.67\"/>" + "<particleLifespanVariance value=\"0.96\"/>" + "<angle value=\"182.69\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"-105.23\" y=\"-0.58\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"1\" blue=\"1\" alpha=\"0.8\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"8.00\"/>" + "<startParticleSize value=\"10.43\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"4.43\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"100\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "<texture name=\"texture.png\"/>" + "</particleEmitterConfig>";
      
      public function §_-X0§()
      {
         super();
      }
   }
}

