package §_-p2z§
{
   public class §_-G2X§
   {
      
      public static const §_-810§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"10\" y=\"10\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"0.11\"/>" + "<particleLifespanVariance value=\"0.5700000000000001\"/>" + "<angle value=\"270\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0\" y=\"0\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"0.93\" blue=\"0\" alpha=\"0\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"1\" green=\"0.86\" blue=\"0\" alpha=\"1\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"1\"/>" + "<startParticleSize value=\"55\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"60\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"19.23\"/>" + "<maxRadiusVariance value=\"10\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"-24.27\"/>" + "<rotatePerSecondVariance value=\"79.41\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"26.21\"/>" + "</particleEmitterConfig>";
      
      public static const §_-p1P§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"12.5\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"1\"/>" + "<particleLifespanVariance value=\"0.96\"/>" + "<angle value=\"270\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0\" y=\"0\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"0.92\" green=\"0.85\" blue=\"0.14\" alpha=\"1\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"1\" green=\"0.52\" blue=\"0\" alpha=\"0.68\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"28.91\"/>" + "<startParticleSize value=\"26.990000000000002\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"5.12\"/>" + "<FinishParticleSizeVariance value=\"5\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"144.87\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public function §_-G2X§()
      {
         super();
      }
   }
}

