package §_-p2z§
{
   public class §_-Ui§
   {
      
      public static const §_-Zu§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<absolutePosition value=\"0\"></absolutePosition>" + "<yCoordFlipped value=\"-1\"></yCoordFlipped>" + "<sourcePositionVariance x=\"0.00\" y=\"8.00\"></sourcePositionVariance>" + "<speed value=\"302.12\"></speed>" + "<speedVariance value=\"12.23\"></speedVariance>" + "<particleLifeSpan value=\"0.3000\"></particleLifeSpan>" + "<particleLifespanVariance value=\"0.0000\"></particleLifespanVariance>" + "<angle value=\"-180.43\"></angle>" + "<angleVariance value=\"-0.00\"></angleVariance>" + "<gravity x=\"0.00\" y=\"-0.00\"></gravity>" + "<radialAcceleration value=\"-132.92\"></radialAcceleration>" + "<tangentialAcceleration value=\"-0.00\"></tangentialAcceleration>" + "<radialAccelVariance value=\"0.00\"></radialAccelVariance>" + "<tangentialAccelVariance value=\"-0.00\"></tangentialAccelVariance>" + "<startColor red=\"0.15\" green=\"0.33\" blue=\"1.00\" alpha=\"1.00\"></startColor>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></startColorVariance>" + "<finishColor red=\"0.26\" green=\"0.73\" blue=\"0.81\" alpha=\"1.00\"></finishColor>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></finishColorVariance>" + "<maxParticles value=\"261\"></maxParticles>" + "<startParticleSize value=\"0.00\"></startParticleSize>" + "<startParticleSizeVariance value=\"75.08\"></startParticleSizeVariance>" + "<finishParticleSize value=\"0.00\"></finishParticleSize>" + "<finishParticleSizeVariance value=\"0.00\"></finishParticleSizeVariance>" + "<duration value=\"-1.00\"></duration>" + "<emitterType value=\"0\"></emitterType>" + "<maxRadius value=\"115.54\"></maxRadius>" + "<maxRadiusVariance value=\"3.00\"></maxRadiusVariance>" + "<minRadius value=\"0.00\"></minRadius>" + "<minRadiusVariance value=\"0.00\"></minRadiusVariance>" + "<rotatePerSecond value=\"0.00\"></rotatePerSecond>" + "<rotatePerSecondVariance value=\"0.00\"></rotatePerSecondVariance>" + "<blendFuncSource value=\"770\"></blendFuncSource>" + "<blendFuncDestination value=\"1\"></blendFuncDestination>" + "<rotationStart value=\"360.00\"></rotationStart>" + "<rotationStartVariance value=\"360.00\"></rotationStartVariance>" + "<rotationEnd value=\"0.00\"></rotationEnd>" + "<rotationEndVariance value=\"0.00\"></rotationEndVariance>" + "</particleEmitterConfig>";
      
      public static const §_-I18§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<absolutePosition value=\"0\"></absolutePosition>" + "<yCoordFlipped value=\"-1\"></yCoordFlipped>" + "<sourcePositionVariance x=\"0.00\" y=\"8.00\"></sourcePositionVariance>" + "<speed value=\"302.12\"></speed>" + "<speedVariance value=\"12.23\"></speedVariance>" + "<particleLifeSpan value=\"0.3000\"></particleLifeSpan>" + "<particleLifespanVariance value=\"0.0000\"></particleLifespanVariance>" + "<angle value=\"-180.43\"></angle>" + "<angleVariance value=\"-0.00\"></angleVariance>" + "<gravity x=\"0.00\" y=\"-0.00\"></gravity>" + "<radialAcceleration value=\"-132.92\"></radialAcceleration>" + "<tangentialAcceleration value=\"-0.00\"></tangentialAcceleration>" + "<radialAccelVariance value=\"0.00\"></radialAccelVariance>" + "<tangentialAccelVariance value=\"-0.00\"></tangentialAccelVariance>" + "<startColor red=\"0.65\" green=\"0.33\" blue=\"0.60\" alpha=\"1.00\"></startColor>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></startColorVariance>" + "<finishColor red=\"0.8\" green=\"0.33\" blue=\"0.50\" alpha=\"1.00\"></finishColor>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></finishColorVariance>" + "<maxParticles value=\"261\"></maxParticles>" + "<startParticleSize value=\"0.00\"></startParticleSize>" + "<startParticleSizeVariance value=\"75.08\"></startParticleSizeVariance>" + "<finishParticleSize value=\"0.00\"></finishParticleSize>" + "<finishParticleSizeVariance value=\"0.00\"></finishParticleSizeVariance>" + "<duration value=\"-1.00\"></duration>" + "<emitterType value=\"0\"></emitterType>" + "<maxRadius value=\"115.54\"></maxRadius>" + "<maxRadiusVariance value=\"3.00\"></maxRadiusVariance>" + "<minRadius value=\"0.00\"></minRadius>" + "<minRadiusVariance value=\"0.00\"></minRadiusVariance>" + "<rotatePerSecond value=\"0.00\"></rotatePerSecond>" + "<rotatePerSecondVariance value=\"0.00\"></rotatePerSecondVariance>" + "<blendFuncSource value=\"770\"></blendFuncSource>" + "<blendFuncDestination value=\"1\"></blendFuncDestination>" + "<rotationStart value=\"360.00\"></rotationStart>" + "<rotationStartVariance value=\"360.00\"></rotationStartVariance>" + "<rotationEnd value=\"0.00\"></rotationEnd>" + "<rotationEndVariance value=\"0.00\"></rotationEndVariance>" + "</particleEmitterConfig>";
      
      public function §_-Ui§()
      {
         super();
      }
   }
}

