package §_-X1k§
{
   public class §_-i1A§
   {
      
      public function §_-i1A§()
      {
         super();
      }
      
      public static function get data() : Object
      {
         return {
            "vip":[{
               "coins_price":10,
               "duration":86400
            },{
               "coins_price":56,
               "duration":604800
            },{
               "coins_price":199,
               "duration":2592000
            },{
               "coins_price":0,
               "duration":3600
            },{
               "coins_price":0,
               "duration":86400
            }],
            "virality":{
               "quests":[5,2,3,4,0,1],
               "bonuses":[{
                  "energy":4,
                  "mana":5
               },{
                  "energy":6,
                  "mana":5
               },{
                  "energy":5,
                  "mana":5
               },{
                  "energy":5,
                  "mana":5
               },{
                  "energy":10,
                  "mana":10
               }]
            },
            "items":{"info":[{
               "nuts_price":300,
               "coins_set_price":5,
               "fast_coins_price":3,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":300,
               "coins_set_price":5,
               "fast_coins_price":3,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":300,
               "coins_set_price":5,
               "fast_coins_price":3,
               "fast_count":5
            },{
               "nuts_price":600,
               "coins_set_price":10,
               "fast_coins_price":5,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":600,
               "coins_set_price":10,
               "fast_coins_price":5,
               "fast_count":5
            },{
               "nuts_price":600,
               "coins_set_price":10,
               "fast_coins_price":5,
               "fast_count":5
            },{
               "nuts_price":600,
               "coins_set_price":10,
               "fast_coins_price":5,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":150,
               "coins_set_price":5,
               "fast_coins_price":3,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":600,
               "coins_set_price":10,
               "fast_coins_price":5,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":150,
               "coins_set_price":5,
               "fast_coins_price":3,
               "fast_count":5
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            },{
               "nuts_price":0,
               "coins_set_price":0,
               "fast_coins_price":0,
               "fast_count":0
            }]},
            "smiles":{"packages":[{
               "coins_price":49,
               "nuts_price":0,
               "elements":[0,1,2,3,4,5,6,7,8,9,25,26,27,28]
            },{
               "coins_price":0,
               "nuts_price":0,
               "elements":[10,11,12,13,14]
            },{
               "coins_price":50,
               "nuts_price":0,
               "elements":[15,16,17,18,19,20,21,22,23,24]
            }]},
            "bans":{"bans":[{
               "title":gls("Нет бана"),
               "hide":true
            },{
               "title":gls("Флуд"),
               "hide":false
            },{
               "title":gls("Нарушение в чате"),
               "hide":false
            },{
               "title":gls("Ненорматив в имени"),
               "hide":false
            },{
               "title":gls("Грубое нарушение на карте"),
               "hide":false
            },{
               "title":gls("Использование стороннего ПО"),
               "hide":false
            },{
               "title":gls("Использование стороннего ПО"),
               "hide":true
            },{
               "title":gls("Использование стороннего ПО"),
               "hide":true
            },{
               "title":gls("Использование стороннего ПО"),
               "hide":true
            },{
               "title":gls("Грубое нарушение в чате"),
               "hide":true
            },{
               "title":gls("Использование стороннего ПО"),
               "hide":true
            },{
               "title":gls("Использование стороннего ПО"),
               "hide":true
            },{
               "title":gls("Оскорбление администрации"),
               "hide":true
            },{
               "title":gls("Нарушение условий лицензионного соглашения"),
               "hide":true
            },{
               "title":gls("Повторное использование стороннего ПО"),
               "hide":true
            },{
               "title":gls("Нарушение условий лицензионного соглашения"),
               "hide":true
            }]},
            "maps":{
               "ADDITION_NUTS_PRICE":200,
               "locations":[{
                  "energy_price":10,
                  "energy_refund_ratio":0.5,
                  "min_level":0,
                  "addition_nuts_award":3500,
                  "is_gaming":true
               },{
                  "energy_price":10,
                  "energy_refund_ratio":0.5,
                  "min_level":8,
                  "addition_nuts_award":3500,
                  "is_gaming":true
               },{
                  "energy_price":10,
                  "energy_refund_ratio":0.5,
                  "min_level":14,
                  "addition_nuts_award":5000,
                  "is_gaming":true
               },{
                  "energy_price":10,
                  "energy_refund_ratio":1,
                  "min_level":21,
                  "addition_nuts_award":7500,
                  "is_gaming":true
               },{
                  "energy_price":10,
                  "energy_refund_ratio":1,
                  "min_level":32,
                  "addition_nuts_award":6500,
                  "is_gaming":true
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":10,
                  "energy_refund_ratio":1,
                  "min_level":18,
                  "addition_nuts_award":10000,
                  "is_gaming":true
               },{
                  "energy_price":15,
                  "energy_refund_ratio":0.5,
                  "min_level":0,
                  "addition_nuts_award":10000,
                  "is_gaming":true
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":10,
                  "energy_refund_ratio":1,
                  "min_level":27,
                  "addition_nuts_award":6500,
                  "is_gaming":true
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":10,
                  "energy_refund_ratio":0,
                  "min_level":7,
                  "addition_nuts_award":0,
                  "is_gaming":true
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":0,
                  "energy_refund_ratio":0,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":false
               },{
                  "energy_price":10,
                  "energy_refund_ratio":0.5,
                  "min_level":0,
                  "addition_nuts_award":0,
                  "is_gaming":true
               }],
               "location_round_info":[{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               }],
               "mode_round_info":[{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":true,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":true,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":true,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":true,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               },{
                  "valid":true,
                  "has_shaman":true,
                  "has_buying_dragon":true,
                  "has_buying_hare":false,
                  "has_buying_shaman":true,
                  "has_many_hares":false
               }],
               "default_round_info":{
                  "valid":false,
                  "has_shaman":false,
                  "has_buying_dragon":false,
                  "has_buying_hare":false,
                  "has_buying_shaman":false,
                  "has_many_hares":false
               }
            },
            "room":{"respawns_duration":[0,0,3,0,5,3,3,3,0,0,0,0]},
            "searching":{},
            "quest":{
               "MIN_LEVEL":4,
               "quests":[[[5,4,4,3,2,0,0,0,0,0,0,0,0,3,0,0,0,0,0],[5,5,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],[20,18,15,8,5,0,0,0,0,0,0,0,0,7,0,0,0,0,0],[6,5,4,2,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0],[5,4,4,3,1,0,0,0,0,0,0,0,0,3,0,0,0,0,0],[20,18,15,8,5,0,0,0,0,0,0,0,0,7,0,0,0,0,0],[5,4,4,3,1,0,0,0,0,0,0,0,0,3,0,0,0,0,0],[20,18,15,8,4,0,0,0,0,0,0,0,0,7,0,0,0,0,0],[7,6,6,5,4,0,0,0,0,0,0,0,0,5,0,0,0,0,0],[5,4,4,3,1,0,0,0,0,0,0,0,0,3,0,0,0,0,0],[5,4,4,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[5,4,4,2,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0],[0,5,5,10,10,0,0,0,0,0,0,0,0,10,0,0,0,0,0]],[[10,8,8,6,4,0,0,0,0,0,0,0,0,6,0,0,0,0,0],[10,10,10,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0],[30,28,25,18,14,0,0,0,0,0,0,0,0,16,0,0,0,0,0],[15,12,8,6,3,0,0,0,0,0,0,0,0,6,0,0,0,0,0],[10,8,8,6,2,0,0,0,0,0,0,0,0,6,0,0,0,0,0],[30,28,25,18,14,0,0,0,0,0,0,0,0,16,0,0,0,0,0],[10,8,8,6,2,0,0,0,0,0,0,0,0,6,0,0,0,0,0],[40,36,34,28,20,0,0,0,0,0,0,0,0,26,0,0,0,0,0],[15,12,12,10,8,0,0,0,0,0,0,0
               ,0,10,0,0,0,0,0],[10,8,8,6,2,0,0,0,0,0,0,0,0,6,0,0,0,0,0],[10,8,8,6,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[10,8,8,5,3,0,0,0,0,0,0,0,0,5,0,0,0,0,0],[0,15,15,30,30,0,0,0,0,0,0,0,0,30,0,0,0,0,0]]],
               "awards":[{
                  "nuts":50,
                  "mana":30,
                  "experience":[{
                     "min_level":0,
                     "experience":30
                  },{
                     "min_level":8,
                     "experience":50
                  },{
                     "min_level":14,
                     "experience":70
                  },{
                     "min_level":18,
                     "experience":120
                  }]
               },{
                  "nuts":80,
                  "mana":40,
                  "experience":[{
                     "min_level":0,
                     "experience":60
                  },{
                     "min_level":8,
                     "experience":100
                  },{
                     "min_level":14,
                     "experience":140
                  },{
                     "min_level":18,
                     "experience":240
                  }]
               }]
            },
            "interior":{
               "decorations":[{
                  "type":0,
                  "coins_price":0,
                  "nuts_price":0
               },{
                  "type":0,
                  "coins_price":32,
                  "nuts_price":5000
               },{
                  "type":0,
                  "coins_price":35,
                  "nuts_price":0
               },{
                  "type":1,
                  "coins_price":0,
                  "nuts_price":0
               },{
                  "type":1,
                  "coins_price":23,
                  "nuts_price":3000
               },{
                  "type":1,
                  "coins_price":25,
                  "nuts_price":0
               },{
                  "type":2,
                  "coins_price":9,
                  "nuts_price":1000
               },{
                  "type":2,
                  "coins_price":15,
                  "nuts_price":2000
               },{
                  "type":2,
                  "coins_price":19,
                  "nuts_price":0
               },{
                  "type":3,
                  "coins_price":0,
                  "nuts_price":0
               },{
                  "type":3,
                  "coins_price":35,
                  "nuts_price":5000
               },{
                  "type":3,
                  "coins_price":39,
                  "nuts_price":0
               },{
                  "type":4,
                  "coins_price":29,
                  "nuts_price":4000
               },{
                  "type":4,
                  "coins_price":32,
                  "nuts_price":5000
               },{
                  "type":4,
                  "coins_price":35,
                  "nuts_price":0
               },{
                  "type":5,
                  "coins_price":0,
                  "nuts_price":0
               },{
                  "type":5,
                  "coins_price":15,
                  "nuts_price":2000
               },{
                  "type":5,
                  "coins_price":15,
                  "nuts_price":0
               },{
                  "type":6,
                  "coins_price":9,
                  "nuts_price":1000
               },{
                  "type":6,
                  "coins_price":15,
                  "nuts_price":2000
               },{
                  "type":6,
                  "coins_price":19,
                  "nuts_price":0
               },{
                  "type":7,
                  "coins_price":0,
                  "nuts_price":0
               },{
                  "type":7,
                  "coins_price":46,
                  "nuts_price":6000
               },{
                  "type":7,
                  "coins_price":49,
                  "nuts_price":0
               },{
                  "type":8,
                  "coins_price":8,
                  "nuts_price":1000
               },{
                  "type":8,
                  "coins_price":15,
                  "nuts_price":2000
               },{
                  "type":8,
                  "coins_price":19,
                  "nuts_price":0
               },{
                  "type":9,
                  "coins_price":7,
                  "nuts_price":1000
               },{
                  "type":9,
                  "coins_price":7,
                  "nuts_price":1000
               },{
                  "type":9,
                  "coins_price":9,
                  "nuts_price":0
               },{
                  "type":10,
                  "coins_price":15,
                  "nuts_price":2000
               },{
                  "type":10,
                  "coins_price":23,
                  "nuts_price":3000
               },{
                  "type":10,
                  "coins_price":25,
                  "nuts_price":0
               },{
                  "type":11,
                  "coins_price":23,
                  "nuts_price":3000
               },{
                  "type":11,
                  "coins_price":29,
                  "nuts_price":4000
               },{
                  "type":11,
                  "coins_price":29,
                  "nuts_price":0
               },{
                  "type":12,
                  "coins_price":29,
                  "nuts_price":4000
               },{
                  "type":12,
                  "coins_price":39,
                  "nuts_price":5000
               },{
                  "type":12,
                  "coins_price":39,
                  "nuts_price":0
               }],
               "default_set":[0,3,9,15,21]
            },
            "shaman":{
               "MAX_LEVEL":50,
               "SKILL_FREE_LEVELS":3,
               "SKILL_PAID_LEVELS":3,
               "PAID_PER_FEATHERS":2,
               "levels":[80,300,720,1400,2400,3780,5600,7920,10800,14300,18480,23400,29120,35700,40044,45408,52152,60636,71220,84264,100128,119172,141756,168240,198984,234348,274692,320376,371760,403274,436469,471883,510058,551532,596846,646541,701155,761230,827304,899918,979613,1066927,1162402,1266576,1330905,1399713,1474442,1556531,1647419,1748548],
               "learn_coins_price":[[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[50,50,5],[50,50,5],[50,50,5],[70,70,5],[70,70,5],[70,70,5],[70,70,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[50,50,5],[50,50,5],[50,50,5],[70,70,5],[70,70,5],[70,70,5],[70,70,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[0,0,0],[35,35,5],[35,35,5],[35,35,5],[35,35,5],[50,50,5],[50,50,5],[50,50,5],[70,70,5],[70,70,5],[70,70,5],[70,70,5]]
            },
            "achievements":{},
            "collections":{
               "unique_set":[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],[25,26,27,28,29],[30,31,32,33,34],[35,36,37,38,39],[40,41,42,43,44],[45,46,47,48,49],[],[55,56,57,58,59],[60,61,62,63,64],[],[],[],[],[],[70,71,72,73,74],[75,76,77,78,79],[80,81,82,83,84],[85,86,87,88,89],[90,91,92,93,94],[95,96,97,98,99],[100,101,102,103,104],[105,106,107,108,109],[110,111,112,113,114],[115,116,117,118,119],[120,121,122,123,124],[125,126,127,128,129],[130,131,132,133,134],[135,136,137,138,139],[140,141,142,143,144],[145,146,147,148,149],[150,151,152,153,154],[155,156,157,158,159],[160,161,162,163,164],[165,166,167,168,169]],
               "trophy_set":[[0,1,2,3,4,5,6,7,24,25,20,21,34,35],[],[0,1,2,3,4,5,6,7,26,27,22,23,36,37],[6,7,28,29,32,33,30,31,26,27,20,21,34,36],[6,7,28,29,32,33,30,31,26,27,20,21,34,36],[5,6,19,28,12,32,9,30,24,27,20,23,35,37],[5,6,19,28,12,32,9,30,24,27,20,23,35,37],[4,7,18,29,11,33,8,31,24,25,22,23,34,36],[4,7,18,29,11,33,8,31,24,25,22,23,34,36],[6,7,28,29,32,33,30,31,25,26,21,22,35,37],[6,7,28,29,32,33,30,31,25,26,21,22,35,37],[6,7,28,29,11,12,8,9,26,27,22,23,34,36],[6,7,28,29,11,12,8,9,26,27,22,23,34,36],[4,5,18,19,32,33,30,31,24,25,20,21,35,37],[4,5,18,19,32,33,30,31,24,25,20,21,35,37],[5,6,19,28,12,32,9,30,25,26,20,23,34,36],[5,6,19,28,12,32,9,30,25,26,20,23,34,36],[5,6,19,28,12,32,9,30,24,27,21,22,35,37],[5,6,19,28,12,32,9,30,24,27,21,22,35,37]],
               "regular_coins_price":[10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,45,45,45,45,45,45,45,45,45,45,0,0,0,0,0,30,30,30,30,30,30,30,30,30,30,0,0,0,0,0,40,40,40,40,40,40,40,40,40,40,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,40,40,40,40,40,40,40,40,40,40,45,45,45,45,45,45,45,45,45,45,30,30,30,30,30,30,30,30,30,30,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25],
               "unique_experience":[500,500,750,750,1000,1000,1000,1000,2500,2500,0,2000,2000,0,0,0,0,0,1500,1500,500,500,500,500,1500,1500,1500,1500,1500,1500,2500,2500,2000,2000]
            },
            "replays":{},
            "chat":{},
            "training":{},
            "ratings":{"leagues":[[{
               "name":gls("Нет"),
               "min_scores":0
            },{
               "name":gls("Бронза"),
               "min_scores":500
            },{
               "name":gls("Серебро"),
               "min_scores":2500
            },{
               "name":gls("Золото"),
               "min_scores":6000
            },{
               "name":gls("Мастер"),
               "min_scores":10000
            },{
               "name":gls("Алмаз"),
               "min_scores":50000
            },{
               "name":gls("Чемпион"),
               "min_scores":100000
            }],[{
               "name":gls("Нет"),
               "min_scores":0
            },{
               "name":gls("Бронза"),
               "min_scores":3750
            },{
               "name":gls("Серебро"),
               "min_scores":18750
            },{
               "name":gls("Золото"),
               "min_scores":45000
            },{
               "name":gls("Мастер"),
               "min_scores":75000
            },{
               "name":gls("Алмаз"),
               "min_scores":375000
            },{
               "name":gls("Чемпион"),
               "min_scores":750000
            }]]}
         };
      }
   }
}

