package §_-eR§
{
   public class §_-v2I§
   {
      
      public static const §_-53s§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"37.5\" y=\"50\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"0.05\"/>" + "<particleLifespanVariance value=\"0.4607\"/>" + "<angle value=\"261.67\"/>" + "<angleVariance value=\"11.43\"/>" + "<gravity x=\"0\" y=\"-100\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"0.68\" green=\"0.34\" blue=\"0.28\" alpha=\"1\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"0.64\" green=\"0.37\" blue=\"0.18\" alpha=\"0.76\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"58\"/>" + "<startParticleSize value=\"16.7\"/>" + "<startParticleSizeVariance value=\"57.5\"/>" + "<finishParticleSize value=\"6.83\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"0\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"82.14\"/>" + "<rotatePerSecondVariance value=\"38.1\"/>" + "<blendFuncSource value=\"770\"/>" + "<blendFuncDestination value=\"1\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public static const §_-71§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"0.00\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"2.0000\"/>" + "<particleLifespanVariance value=\"1.9000\"/>" + "<angle value=\"360\"/>" + "<angleVariance value=\"2.00\"/>" + "<gravity x=\"0\" y=\"46.51\"/>" + "<radialAcceleration value=\"0.00\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0.00\"/>" + "<tangentialAccelVariance value=\"223.88\"/>" + "<startColor red=\"0.13\" green=\"0.6\" blue=\"0.7000000000000001\" alpha=\"0.62\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColor red=\"0.43\" green=\"0.63\" blue=\"0.65\" alpha=\"0.65\"/>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<maxParticles value=\"45.07\"/>" + "<startParticleSize value=\"3.37\"/>" + "<startParticleSizeVariance value=\"49.53\"/>" + "<finishParticleSize value=\"35.550000000000004\"/>" + "<FinishParticleSizeVariance value=\"50\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"260.26\"/>" + "<maxRadiusVariance value=\"102.04\"/>" + "<minRadius value=\"67.9\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0.00\"/>" + "<blendFuncSource value=\"770\"/>" + "<blendFuncDestination value=\"1\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0.00\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0.00\"/>" + "</particleEmitterConfig>";
      
      public function §_-v2I§()
      {
         super();
      }
   }
}

