package §_-eR§
{
   public class §_-m1w§
   {
      
      public static const §_-2f§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"0.00\" y=\"0.00\"/>" + "<speed value=\"20\"/>" + "<speedVariance value=\"5.00\"/>" + "<particleLifeSpan value=\"2.0\"/>" + "<particleLifespanVariance value=\"1.0\"/>" + "<angle value=\"270.00\"/>" + "<angleVariance value=\"2.00\"/>" + "<gravity x=\"0.00\" y=\"0.00\"/>" + "<radialAcceleration value=\"0.00\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0.00\"/>" + "<tangentialAccelVariance value=\"0.00\"/>" + "<startColor red=\"0\" green=\"0\" blue=\"0\" alpha=\"0.8\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.40\"/>" + "<finishColor red=\"0\" green=\"0\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<maxParticles value=\"1\"/>" + "<startParticleSize value=\"20\"/>" + "<startParticleSizeVariance value=\"5\"/>" + "<finishParticleSize value=\"40\"/>" + "<FinishParticleSizeVariance value=\"10\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"100.00\"/>" + "<maxRadiusVariance value=\"0.00\"/>" + "<minRadius value=\"0.00\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0.00\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"144.88\"/>" + "<rotationStartVariance value=\"0.00\"/>" + "<rotationEnd value=\"210.34\"/>" + "<rotationEndVariance value=\"0.00\"/>" + "</particleEmitterConfig>";
      
      public static const §_-O3§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"0.00\" y=\"0.00\"/>" + "<speed value=\"250\"/>" + "<speedVariance value=\"25.00\"/>" + "<particleLifeSpan value=\"3.0\"/>" + "<particleLifespanVariance value=\"1\"/>" + "<angle value=\"270.00\"/>" + "<angleVariance value=\"5.00\"/>" + "<gravity x=\"0.00\" y=\"0.00\"/>" + "<radialAcceleration value=\"0.00\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0.00\"/>" + "<tangentialAccelVariance value=\"0.00\"/>" + "<startColor red=\"0.8\" green=\"0.8\" blue=\"0.4\" alpha=\"1\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColor red=\"0.4\" green=\"0.4\" blue=\"0.20\" alpha=\"0.0\"/>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<maxParticles value=\"30\"/>" + "<startParticleSize value=\"35\"/>" + "<startParticleSizeVariance value=\"10\"/>" + "<finishParticleSize value=\"45\"/>" + "<FinishParticleSizeVariance value=\"10\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"100.00\"/>" + "<maxRadiusVariance value=\"0.00\"/>" + "<minRadius value=\"0.00\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0.00\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"0.00\"/>" + "<rotationStartVariance value=\"0.00\"/>" + "<rotationEnd value=\"0.00\"/>" + "<rotationEndVariance value=\"0.00\"/>" + "</particleEmitterConfig>";
      
      public static const §_-D2H§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"0.00\" y=\"0.00\"/>" + "<sourcePositionVariance x=\"0.00\" y=\"0.00\"/>" + "<speed value=\"500\"/>" + "<speedVariance value=\"100.00\"/>" + "<particleLifeSpan value=\"9.00\"/>" + "<particleLifespanVariance value=\"0\"/>" + "<angle value=\"270.00\"/>" + "<angleVariance value=\"2.00\"/>" + "<gravity x=\"0.00\" y=\"0.00\"/>" + "<radialAcceleration value=\"0.00\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0.00\"/>" + "<tangentialAccelVariance value=\"0.00\"/>" + "<startColor red=\"1\" green=\"1.0\" blue=\"1.0\" alpha=\"1\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColor red=\"0\" green=\"0\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<maxParticles value=\"350\"/>" + "<startParticleSize value=\"75.0\"/>" + "<startParticleSizeVariance value=\"10\"/>" + "<finishParticleSize value=\"85.0\"/>" + "<FinishParticleSizeVariance value=\"10\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"600.00\"/>" + "<maxRadiusVariance value=\"0.00\"/>" + "<minRadius value=\"0.00\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0.00\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"276.59000000000003\"/>" + "<rotationStartVariance value=\"94.43\"/>" + "<rotationEnd value=\"210.34\"/>" + "<rotationEndVariance value=\"0.00\"/>" + "</particleEmitterConfig>";
      
      public function §_-m1w§()
      {
         super();
      }
   }
}

