package §_-eR§
{
   public class §_-F1M§
   {
      
      public static const §_-CJ§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"0\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"30\"/>" + "<particleLifeSpan value=\"0.58\"/>" + "<particleLifespanVariance value=\"1.9\"/>" + "<angle value=\"270\"/>" + "<angleVariance value=\"2\"/>" + "<gravity x=\"0\" y=\"-104.65\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"0.1\" blue=\"0\" alpha=\"0.7000000000000001\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"1\" green=\"0.01\" blue=\"0\" alpha=\"0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"103.1\"/>" + "<startParticleSize value=\"70\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"5.12\"/>" + "<FinishParticleSizeVariance value=\"5\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"144.87\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"770\"/>" + "<blendFuncDestination value=\"1\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public static const §_-Lu§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"0\" y=\"0\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"30\"/>" + "<particleLifeSpan value=\"0.58\"/>" + "<particleLifespanVariance value=\"1.9\"/>" + "<angle value=\"270\"/>" + "<angleVariance value=\"2\"/>" + "<gravity x=\"0\" y=\"-104.65\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"0\" green=\"1\" blue=\"1\" alpha=\"0.86\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"0\" green=\"0.21\" blue=\"0.6900000000000001\" alpha=\"0.12\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"103.1\"/>" + "<startParticleSize value=\"70\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"5.12\"/>" + "<FinishParticleSizeVariance value=\"5\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"144.87\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"770\"/>" + "<blendFuncDestination value=\"1\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public function §_-F1M§()
      {
         super();
      }
   }
}

