package §_-eR§
{
   public class §_-03i§
   {
      
      public static const §_-I11§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"62.5\" y=\"50\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"7.97\"/>" + "<particleLifespanVariance value=\"4.97\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0.00\" y=\"0.00\"/>" + "<radialAcceleration value=\"-5.88\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0.00\"/>" + "<startColor red=\"0\" green=\"0\" blue=\"0.00\" alpha=\"0\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColor red=\"0.50\" green=\"0\" blue=\"0.50\" alpha=\"1\"/>" + "<finishColorVariance red=\"0.10\" green=\"0.10\" blue=\"0.10\" alpha=\"0.00\"/>" + "<maxParticles value=\"70\"/>" + "<startParticleSize value=\"20\"/>" + "<startParticleSizeVariance value=\"5\"/>" + "<finishParticleSize value=\"50\"/>" + "<FinishParticleSizeVariance value=\"20\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"0\"/>" + "<maxRadiusVariance value=\"0.00\"/>" + "<minRadius value=\"0.00\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"87.8\"/>" + "<rotationStartVariance value=\"141.64000000000001\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"195.88\"/>" + "</particleEmitterConfig>";
      
      public static const §_-229§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"62.5\" y=\"50\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"8\"/>" + "<particleLifespanVariance value=\"5\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0.00\" y=\"0.00\"/>" + "<radialAcceleration value=\"-5.88\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0.00\"/>" + "<startColor red=\"0\" green=\"0\" blue=\"0.00\" alpha=\"0\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColor red=\"0.90\" green=\"0.8\" blue=\"0.30\" alpha=\"1\"/>" + "<finishColorVariance red=\"0.10\" green=\"0.10\" blue=\"0.10\" alpha=\"0.00\"/>" + "<maxParticles value=\"70\"/>" + "<startParticleSize value=\"20\"/>" + "<startParticleSizeVariance value=\"5\"/>" + "<finishParticleSize value=\"50\"/>" + "<FinishParticleSizeVariance value=\"20\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"0\"/>" + "<maxRadiusVariance value=\"0.00\"/>" + "<minRadius value=\"0.00\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"87.8\"/>" + "<rotationStartVariance value=\"141.64000000000001\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"195.88\"/>" + "</particleEmitterConfig>";
      
      public static const §_-82b§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"25\" y=\"50\"/>" + "<speed value=\"92.05\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"3.04\"/>" + "<particleLifespanVariance value=\"0\"/>" + "<angle value=\"86.3\"/>" + "<angleVariance value=\"360\"/>" + "<gravity x=\"0\" y=\"0\"/>" + "<radialAcceleration value=\"0\"/>" + "<tangentialAcceleration value=\"0\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"0\" green=\"0.64\" blue=\"0.3\" alpha=\"0.83\"/>" + "<startColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<finishColor red=\"0.32\" green=\"0.6\" blue=\"0.74\" alpha=\"0.0\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"308.05\"/>" + "<startParticleSize value=\"59.04\"/>" + "<startParticleSizeVariance value=\"0\"/>" + "<finishParticleSize value=\"225.16\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"3\"/>" + "<maxRadiusVariance value=\"3\"/>" + "<minRadius value=\"0\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"0\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"1\"/>" + "<rotationStart value=\"0\"/>" + "<rotationStartVariance value=\"0\"/>" + "<rotationEnd value=\"0\"/> " + "<rotationEndVariance value=\"0\"/>" + "</particleEmitterConfig>";
      
      public static const §_-eF§:String = "<particleEmitterConfig>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"62.5\" y=\"50\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"7.97\"/>" + "<particleLifespanVariance value=\"4.97\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0.00\" y=\"0.00\"/>" + "<radialAcceleration value=\"-5.88\"/>" + "<tangentialAcceleration value=\"0.00\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0.00\"/>" + "<startColor red=\"0\" green=\"0\" blue=\"0.00\" alpha=\"0\"/>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<finishColor red=\"0.00\" green=\"0\" blue=\"0.00\" alpha=\"1\"/>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"/>" + "<maxParticles value=\"70\"/>" + "<startParticleSize value=\"20\"/>" + "<startParticleSizeVariance value=\"5\"/>" + "<finishParticleSize value=\"50\"/>" + "<FinishParticleSizeVariance value=\"20\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"0\"/>" + "<maxRadius value=\"0\"/>" + "<maxRadiusVariance value=\"0.00\"/>" + "<minRadius value=\"0.00\"/>" + "<minRadiusVariance value=\"0.00\"/>" + "<rotatePerSecond value=\"0.00\"/>" + "<rotatePerSecondVariance value=\"0\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"87.8\"/>" + "<rotationStartVariance value=\"141.64000000000001\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"195.88\"/>" + "</particleEmitterConfig>";
      
      public static const §_-r2C§:String = "<particleEmitterConfig>" + "<absolutePosition value=\"0\"></absolutePosition>" + "<yCoordFlipped value=\"1\"></yCoordFlipped>" + "<sourcePosition x=\"0.00\" y=\"0.00\"></sourcePosition>" + "<sourcePositionVariance x=\"0.00\" y=\"0.00\"></sourcePositionVariance>" + "<speed value=\"91.52\"></speed>" + "<speedVariance value=\"63.78\"></speedVariance>" + "<particleLifeSpan value=\"1.1717\"></particleLifeSpan>" + "<particleLifespanVariance value=\"0.0442\"></particleLifespanVariance>" + "<angle value=\"279.65\"></angle>" + "<angleVariance value=\"210.71\"></angleVariance>" + "<gravity x=\"0\" y=\"0\"></gravity>" + "<radialAcceleration value=\"170.03\"></radialAcceleration>" + "<tangentialAcceleration value=\"-39.47\"></tangentialAcceleration>" + "<radialAccelVariance value=\"-86.28\"></radialAccelVariance>" + "<tangentialAccelVariance value=\"13.00\"></tangentialAccelVariance>" + "<startColor red=\"0.50\" green=\"1.0\" blue=\"0.5\" alpha=\"1.00\"></startColor>" + "<startColorVariance red=\"0.02\" green=\"0.00\" blue=\"0.02\" alpha=\"0.00\"></startColorVariance>" + "<finishColor red=\"0.5\" green=\"1.00\" blue=\"0.5\" alpha=\"0.00\"></finishColor>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></finishColorVariance>" + "<maxParticles value=\"40\"></maxParticles>" + "<startParticleSize value=\"50.00\"></startParticleSize>" + "<startParticleSizeVariance value=\"10.00\"></startParticleSizeVariance>" + "<finishParticleSize value=\"10.00\"></finishParticleSize>" + "<finishParticleSizeVariance value=\"2.00\"></finishParticleSizeVariance>" + "<duration value=\"-1.00\"></duration>" + "<emitterType value=\"0\"></emitterType>" + "<maxRadius value=\"162.66\"></maxRadius>" + "<maxRadiusVariance value=\"37.97\"></maxRadiusVariance>" + "<minRadius value=\"23.29\"></minRadius>" + "<minRadiusVariance value=\"0.00\"></minRadiusVariance>" + "<rotatePerSecond value=\"0.50\"></rotatePerSecond>" + "<rotatePerSecondVariance value=\"40.58\"></rotatePerSecondVariance>" + "<blendFuncSource value=\"1\"></blendFuncSource>" + "<blendFuncDestination value=\"1\"></blendFuncDestination>" + "<rotationStart value=\"0.00\"></rotationStart>" + "<rotationStartVariance value=\"360.00\"></rotationStartVariance>" + "<rotationEnd value=\"1976.19\"></rotationEnd>" + "<rotationEndVariance value=\"-529.16\"></rotationEndVariance>" + "</particleEmitterConfig>";
      
      public static const §_-N2§:String = "<particleEmitterConfig>" + "<absolutePosition value=\"0\"></absolutePosition>" + "<yCoordFlipped value=\"1\"></yCoordFlipped>" + "<sourcePosition x=\"0.00\" y=\"0.00\"></sourcePosition>" + "<sourcePositionVariance x=\"0.00\" y=\"0.00\"></sourcePositionVariance>" + "<speed value=\"91.52\"></speed>" + "<speedVariance value=\"63.78\"></speedVariance>" + "<particleLifeSpan value=\"1.1717\"></particleLifeSpan>" + "<particleLifespanVariance value=\"0.0442\"></particleLifespanVariance>" + "<angle value=\"279.65\"></angle>" + "<angleVariance value=\"210.71\"></angleVariance>" + "<gravity x=\"0\" y=\"0\"></gravity>" + "<radialAcceleration value=\"170.03\"></radialAcceleration>" + "<tangentialAcceleration value=\"-39.47\"></tangentialAcceleration>" + "<radialAccelVariance value=\"-86.28\"></radialAccelVariance>" + "<tangentialAccelVariance value=\"13.00\"></tangentialAccelVariance>" + "<startColor red=\"1.0\" green=\"0.30\" blue=\"0.80\" alpha=\"1.00\"></startColor>" + "<startColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"1.00\"></startColorVariance>" + "<finishColor red=\"1.00\" green=\"0.30\" blue=\"0.80\" alpha=\"0.00\"></finishColor>" + "<finishColorVariance red=\"0.00\" green=\"0.00\" blue=\"0.00\" alpha=\"0.00\"></finishColorVariance>" + "<maxParticles value=\"40\"></maxParticles>" + "<startParticleSize value=\"50.00\"></startParticleSize>" + "<startParticleSizeVariance value=\"10.00\"></startParticleSizeVariance>" + "<finishParticleSize value=\"10.00\"></finishParticleSize>" + "<finishParticleSizeVariance value=\"2.00\"></finishParticleSizeVariance>" + "<duration value=\"-1.00\"></duration>" + "<emitterType value=\"0\"></emitterType>" + "<maxRadius value=\"162.66\"></maxRadius>" + "<maxRadiusVariance value=\"37.97\"></maxRadiusVariance>" + "<minRadius value=\"23.29\"></minRadius>" + "<minRadiusVariance value=\"0.00\"></minRadiusVariance>" + "<rotatePerSecond value=\"0.50\"></rotatePerSecond>" + "<rotatePerSecondVariance value=\"40.58\"></rotatePerSecondVariance>" + "<blendFuncSource value=\"1\"></blendFuncSource>" + "<blendFuncDestination value=\"1\"></blendFuncDestination>" + "<rotationStart value=\"0.00\"></rotationStart>" + "<rotationStartVariance value=\"360.00\"></rotationStartVariance>" + "<rotationEnd value=\"1976.19\"></rotationEnd>" + "<rotationEndVariance value=\"-529.16\"></rotationEndVariance>" + "</particleEmitterConfig>";
      
      public function §_-03i§()
      {
         super();
      }
   }
}

