package §_-eR§
{
   public class §_-G2G§
   {
      
      public static var §_-eu§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"25\" y=\"25\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"2.61\"/>" + "<particleLifespanVariance value=\"0.46\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0\" y=\"-0.58\"/>" + "<radialAcceleration value=\"-382.94\"/>" + "<tangentialAcceleration value=\"-160\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"1\" blue=\"1\" alpha=\"1\"/>" + "<startColorVariance red=\"0.93\" green=\"1\" blue=\"0.48\" alpha=\"1\"/>" + "<finishColor red=\"1\" green=\"1\" blue=\"1\" alpha=\"1\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"45.07\"/>" + "<startParticleSize value=\"15.94\"/>" + "<startParticleSizeVariance value=\"9.77\"/>" + "<finishParticleSize value=\"21.34\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"1\"/>" + "<maxRadius value=\"5.45\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"36.73\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"-4.45\"/>" + "<rotatePerSecondVariance value=\"360\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"118.54\"/>" + "<rotationStartVariance value=\"82.62\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"180\"/>" + "</particleEmitterConfig>";
      
      public static var §_-8w§:String = "<particleEmitterConfig>" + "<texture name=\"texture.png\"/>" + "<sourcePosition x=\"300.00\" y=\"300.00\"/>" + "<sourcePositionVariance x=\"25\" y=\"25\"/>" + "<speed value=\"0\"/>" + "<speedVariance value=\"0\"/>" + "<particleLifeSpan value=\"2.61\"/>" + "<particleLifespanVariance value=\"0.46\"/>" + "<angle value=\"0\"/>" + "<angleVariance value=\"0\"/>" + "<gravity x=\"0\" y=\"-0.58\"/>" + "<radialAcceleration value=\"-382.94\"/>" + "<tangentialAcceleration value=\"-160\"/>" + "<radialAccelVariance value=\"0\"/>" + "<tangentialAccelVariance value=\"0\"/>" + "<startColor red=\"1\" green=\"1\" blue=\"1\" alpha=\"1\"/>" + "<startColorVariance red=\"0.93\" green=\"1\" blue=\"0.48\" alpha=\"1\"/>" + "<finishColor red=\"1\" green=\"1\" blue=\"1\" alpha=\"1\"/>" + "<finishColorVariance red=\"0\" green=\"0\" blue=\"0\" alpha=\"0\"/>" + "<maxParticles value=\"25.00\"/>" + "<startParticleSize value=\"7.94\"/>" + "<startParticleSizeVariance value=\"4.77\"/>" + "<finishParticleSize value=\"11.34\"/>" + "<FinishParticleSizeVariance value=\"0\"/>" + "<duration value=\"-1.00\"/>" + "<emitterType value=\"1\"/>" + "<maxRadius value=\"5.45\"/>" + "<maxRadiusVariance value=\"0\"/>" + "<minRadius value=\"36.73\"/>" + "<minRadiusVariance value=\"0\"/>" + "<rotatePerSecond value=\"-4.45\"/>" + "<rotatePerSecondVariance value=\"360\"/>" + "<blendFuncSource value=\"1\"/>" + "<blendFuncDestination value=\"771\"/>" + "<rotationStart value=\"118.54\"/>" + "<rotationStartVariance value=\"82.62\"/>" + "<rotationEnd value=\"0\"/>" + "<rotationEndVariance value=\"180\"/>" + "</particleEmitterConfig>";
      
      public function §_-G2G§()
      {
         super();
      }
   }
}

